// Headless checks for Stage 5 M3 (node tests/ocean/m3.mjs [seed]): ocean monuments — the room graph, the building
// laid into a made-up sea (walls, rooms, the gold, the sponges, the elders, the pillars, the water it clears), where
// they go on the real biome noise, the guardian spawn override, /locate, and one generated by the real chunk generator.
// Prints a top-down map of that one.
import { loadModules } from '../../scripts/load.mjs';
setTimeout(() => { console.log('TIMEOUT'); process.exit(2); }, 240000).unref();
const seed = process.argv[2] ?? '12345';
const { mods, close } = await loadModules([
  '/src/world/blocks.ts', '/src/world/block.ts', '/src/world/gen/monument.ts', '/src/world/gen/context.ts', '/src/world/constants.ts',
  '/src/core/rng.ts', '/src/world/gen/biomes.ts', '/src/world/gen/router.ts', '/src/world/gen/noise.ts', '/src/game/monuments.ts',
  '/src/game/level.ts', '/src/world/world.ts', '/src/game/spawner.ts', '/src/world/gen/generator.ts', '/src/world/gen/structure.ts',
  '/src/game/structureSpawns.ts',
]);
const [, BM, M, C, K, rng, biomes, router, noise, runtime, levelMod, worldMod, spawner, G, St, SS] = mods;
const { BLOCKS, STATE_BLOCK, S } = BM;
const { B, BIOMES } = biomes;
let fails = 0;
const check = (name, cond, extra = '') => { if (!cond) fails++; console.log(`${cond ? 'ok  ' : 'FAIL'} ${name}${extra ? ' ' + extra : ''}`); };
const name = (st) => BLOCKS[STATE_BLOCK[st]].name;
const CELLS = { SimpleRoom: 1, SimpleTopRoom: 1, EntryRoom: 1, DoubleXRoom: 2, DoubleZRoom: 2, DoubleYRoom: 2, DoubleXYRoom: 4, DoubleYZRoom: 4, CoreRoom: 8 };

// --- the room graph, many times over
{
  const kinds = new Map(), dirs = new Set();
  let bad = [], sponges = 0;
  for (let s = 0; s < 200; s++) {
    const r = new rng.JavaRandom(s * 7919 + 13);
    const dir = ['north', 'east', 'south', 'west'][s % 4];
    const b = new M.MonumentBuilding(r, 1000, -2000, dir);
    dirs.add(b.orientation);
    const ks = b.roomKinds();
    for (const k of ks) kinds.set(k, (kinds.get(k) ?? 0) + 1);
    const count = (k) => ks.filter((x) => x === k).length;
    if (count('EntryRoom') !== 1 || count('CoreRoom') !== 1 || count('WingRoom') !== 2 || count('Penthouse') !== 1) bad.push(`${s}: ${ks.join(',')}`);
    const cells = ks.reduce((n, k) => n + (CELLS[k] ?? 0), 0);
    if (cells !== 46) bad.push(`${s}: ${cells} cells`);
    for (const c of b.children) {
      const x = c.box;
      if (x.minX < b.box.minX || x.maxX > b.box.maxX || x.minZ < b.box.minZ || x.maxZ > b.box.maxZ || x.minY < b.box.minY || x.maxY > b.box.maxY) bad.push(`${s}: ${c.constructor.name} outside`);
    }
    // every cell can still reach the entrance through the ways left open
    let scan = 100000;
    for (const c of b.children) if (c.room && !c.room.findSource(scan++)) bad.push(`${s}: ${c.constructor.name} cut off`);
    if (count('SimpleTopRoom') > 0) sponges++;
  }
  check('a monument: one entrance, one core, two wings, a penthouse, the 46 cells all taken, all inside', bad.length === 0, bad.slice(0, 4).join('; '));
  check('every kind of room turns up', ['SimpleRoom', 'SimpleTopRoom', 'DoubleXRoom', 'DoubleZRoom', 'DoubleYRoom', 'DoubleXYRoom', 'DoubleYZRoom'].every((k) => kinds.get(k) > 0), [...kinds].map(([k, v]) => `${k} ${v}`).join(', '));
  check('sponge rooms in most', sponges > 100, `${sponges}/200`);
}

// --- one laid into a made-up sea
function build(dir, floorY, seedN = 99) {
  const mons = new M.OceanMonuments(BigInt(seedN), () => B.deep_ocean);
  const bld = mons.building(0, 0);
  const b = bld.box;
  const ctxs = new Map();
  for (let cx = (b.minX >> 4) - 1; cx <= (b.maxX >> 4) + 1; cx++)
    for (let cz = (b.minZ >> 4) - 1; cz <= (b.maxZ >> 4) + 1; cz++) {
      const blocks = new Uint16Array(K.COLUMN_VOLUME);
      for (let lx = 0; lx < 16; lx++) for (let lz = 0; lz < 16; lz++) for (let y = 0; y <= 62; y++) blocks[K.colIndex(lx, y, lz)] = y <= floorY ? S('stone') : S('water');
      const ctx = new C.GenContext(cx, cz, blocks, new Uint8Array(256));
      mons.place(ctx);
      ctxs.set(cx + ',' + cz, ctx);
    }
  const at = (x, y, z) => { const c = ctxs.get((x >> 4) + ',' + (z >> 4)); return c ? name(c.blocks[K.colIndex(x & 15, y, z & 15)]) : '?'; };
  return { bld, b, ctxs, at };
}
{
  const { bld, b, ctxs, at } = build(null, 30);
  const tally = new Map();
  for (let x = b.minX - 6; x <= b.maxX + 6; x++) for (let z = b.minZ - 6; z <= b.maxZ + 6; z++) for (let y = 25; y <= 70; y++) { const n = at(x, y, z); tally.set(n, (tally.get(n) ?? 0) + 1); }
  console.log('blocks:', [...tally].filter(([n]) => n !== 'water' && n !== 'stone' && n !== 'air').map(([n, c]) => `${n} ${c}`).join(', '));
  check('prismarine, its bricks, dark prismarine and sea lanterns', tally.get('prismarine') > 5000 && tally.get('prismarine_bricks') > 5000 && tally.get('dark_prismarine') > 100 && tally.get('sea_lantern') > 50);
  const core = bld.children.find((c) => c.constructor.name === 'CoreRoom');
  let gold = 0;
  for (let x = core.box.minX; x <= core.box.maxX; x++) for (let z = core.box.minZ; z <= core.box.maxZ; z++) for (let y = core.box.minY; y <= core.box.maxY; y++) if (at(x, y, z) === 'gold_block') gold++;
  check('eight gold blocks, in the core room', tally.get('gold_block') === 8 && gold === 8);
  const spongeRooms = bld.children.filter((c) => c.constructor.name === 'SimpleTopRoom');
  let wet = 0;
  for (const c of spongeRooms) for (let x = c.box.minX; x <= c.box.maxX; x++) for (let z = c.box.minZ; z <= c.box.maxZ; z++) for (let y = c.box.minY; y <= c.box.maxY; y++) if (at(x, y, z) === 'wet_sponge') wet++;
  check('wet sponges, in the sponge rooms', spongeRooms.length === 0 ? !tally.get('wet_sponge') : wet > 5 * spongeRooms.length && wet === tally.get('wet_sponge'), `${spongeRooms.length} rooms, ${wet}`);
  const elders = [...ctxs.values()].flatMap((c) => c.entities).filter((e) => e.id === 'elder_guardian');
  check('three elder guardians, inside, kept', elders.length === 3 && elders.every((e) => b.isInside(Math.floor(e.x), Math.floor(e.y), Math.floor(e.z)) && e.persistent && e.health === 80), elders.map((e) => `${e.x},${e.y},${e.z}`).join(' '));
  const pent = bld.children.find((c) => c.constructor.name === 'Penthouse');
  check('...one of them in the penthouse', elders.some((e) => pent.box.isInside(Math.floor(e.x), Math.floor(e.y), Math.floor(e.z))));
  let top = 0;
  for (let x = b.minX; x <= b.maxX; x++) for (let z = b.minZ; z <= b.maxZ; z++) for (let y = 70; y >= 39; y--) if (at(x, y, z).startsWith('prismarine') || at(x, y, z) === 'dark_prismarine' || at(x, y, z) === 'sea_lantern') { top = Math.max(top, y); break; }
  check('it tops out at y 61 (the box\'s top)', top <= 61 && top >= 59, `${top}`);
  // the corner pillars reach down to the sea floor
  let pillar = true;
  for (let y = 31; y <= 39; y++) if (at(b.minX, y, b.minZ) !== 'prismarine_bricks') pillar = false;
  check('its pillars go down to the sea floor', pillar && at(b.minX, 30, b.minZ) === 'stone');
  // an entry room: water inside
  const entry = bld.children.find((c) => c.constructor.name === 'EntryRoom');
  const ex = (entry.box.minX + entry.box.maxX) >> 1, ez = (entry.box.minZ + entry.box.maxZ) >> 1;
  check('water in its rooms', at(ex, entry.box.minY + 1, ez) === 'water' && at(ex, entry.box.minY + 2, ez) === 'water');
  const rooms = bld.children.filter((c) => c.room);
  check('the rooms are floored with prismarine', rooms.every((c) => { const y = c.box.minY; return at(c.box.minX, y, c.box.minZ) !== 'water'; }));
}
{
  // a sea floor above the monument's base: cleared out inside and stepping down round it
  const { b, at, bld } = build(null, 46);
  let stone = 0;
  for (let x = b.minX; x <= b.maxX; x++) for (let z = b.minZ; z <= b.maxZ; z++) for (let y = 40; y <= 46; y++) if (at(x, y, z) === 'stone') stone++;
  check('the sea floor inside it is cleared', stone === 0, `${stone} left`);
  // (a side where no rim wall is: the step one out starts at the base, three out at y 43)
  const o = bld.orientation;
  const zc = (b.minZ + b.maxZ) >> 1;
  check('the water steps away round it', at(b.minX - 1, 40, zc) === 'water' && at(b.minX - 3, 42, zc) === 'stone' && at(b.minX - 3, 44, zc) === 'water', `${o}: ${at(b.minX - 1, 40, zc)} ${at(b.minX - 3, 42, zc)} ${at(b.minX - 3, 44, zc)}`);
}

// --- where they go, on the real biome noise
const loc = M.monumentLocator(seed);
{
  const r = new router.OverworldRouter(noise.SeedSource.fromWorldSeed(seed));
  const quart = (x, z) => { const c = r.column(x & ~3, z & ~3, router.newColumn()); return biomes.pickSurfaceBiome(c.temperature, c.humidity, c.continents, c.erosion, c.ridges); };
  const OCEAN = new Set(['ocean', 'deep_ocean', 'cold_ocean', 'deep_cold_ocean', 'lukewarm_ocean', 'deep_lukewarm_ocean', 'warm_ocean', 'frozen_ocean', 'deep_frozen_ocean', 'river', 'frozen_river']);
  let stubs = 0, candidates = 0;
  const bad = [];
  for (let rx = -8; rx < 8; rx++)
    for (let rz = -8; rz < 8; rz++) {
      candidates++;
      const [pcx, pcz] = loc.potentialChunk(rx, rz);
      const ox = pcx - rx * 32, oz = pcz - rz * 32;
      if (ox < 0 || ox > 26 || oz < 0 || oz > 26) bad.push(`offset ${ox},${oz}`);
      const s = loc.stub(rx, rz);
      if (!s) continue;
      stubs++;
      const mid = BIOMES[quart(s.cx * 16 + 8, s.cz * 16 + 8)].name;
      if (!mid.startsWith('deep_')) bad.push(`middle ${mid}`);
      for (let x = s.cx * 16 + 9 - 29; x <= s.cx * 16 + 9 + 29; x += 4)
        for (let z = s.cz * 16 + 9 - 29; z <= s.cz * 16 + 9 + 29; z += 4) if (!OCEAN.has(BIOMES[quart(x, z)].name)) bad.push(`around ${BIOMES[quart(x, z)].name}`);
    }
  check('monuments: spread in their regions, only in deep ocean with nothing but sea within 29', bad.length === 0, bad.slice(0, 4).join('; '));
  check('...some regions have one', stubs > 0, `${stubs}/${candidates}`);
}

// --- the spawn override and /locate
const found = loc.nearest(0, 0);
check('there is a monument to find', !!found, JSON.stringify(found));
{
  const world = new worldMod.World();
  const level = new levelMod.Level(world, seed);
  check('/locate structure monument finds it', JSON.stringify(runtime.locateMonument(level, 0, 0)) === JSON.stringify(found));
  const rx = Math.floor((found[0] >> 4) / 32), rz = Math.floor((found[1] >> 4) / 32);
  const box = loc.building(rx, rz).box;
  const cx = (box.minX + box.maxX) >> 1, cz = (box.minZ + box.maxZ) >> 1;
  const at = (cat, x, y, z) => SS.structureMobsAt(level, cat, x, y, z);
  const sp = at('monster', cx, 50, cz);
  check('inside a monument, the monsters that spawn are guardians, 2 to 4', sp?.length === 1 && sp[0].type === 'guardian' && sp[0].min === 2 && sp[0].max === 4);
  check('...through its whole box', at('monster', box.minX, 39, box.maxZ) !== null && at('monster', box.maxX, 61, box.minZ) !== null);
  check('...and not past it', at('monster', cx, 38, cz) === null && at('monster', cx, 62, cz) === null && at('monster', box.maxX + 1, 50, cz) === null);
  check('...no glow squid or axolotls in it (empty overrides), and the rest as the biome has them', at('underground_water_creature', cx, 50, cz)?.length === 0 && at('axolotls', box.minX, 39, box.minZ)?.length === 0 && at('underground_water_creature', cx, 38, cz) === null && at('creature', cx, 50, cz) === null && at('water_creature', cx, 50, cz) === null && at('water_ambient', cx, 50, cz) === null);
  const ns = new spawner.NaturalSpawner(level, 1);
  check('the natural spawner takes it up', ns.mobsAt('monster', cx, 50, cz)?.[0]?.type === 'guardian');
}

// --- generated by the real chunk generator
{
  const gen = new G.ChunkGenerator(seed);
  const rx = Math.floor((found[0] >> 4) / 32), rz = Math.floor((found[1] >> 4) / 32);
  const bld = gen.monuments.building(rx, rz);
  const b = bld.box;
  const outs = new Map();
  const t0 = performance.now();
  for (let cx = b.minX >> 4; cx <= b.maxX >> 4; cx++) for (let cz = b.minZ >> 4; cz <= b.maxZ >> 4; cz++) outs.set(cx + ',' + cz, gen.generate(cx, cz));
  console.log(`generated ${outs.size} chunks in ${Math.round(performance.now() - t0)} ms (monument at ${b.minX},${b.minZ} facing ${bld.orientation})`);
  const at = (x, y, z) => { const o = outs.get((x >> 4) + ',' + (z >> 4)); return o ? name(o.blocks[K.colIndex(x & 15, y, z & 15)]) : '?'; };
  let gold = 0, lanterns = 0;
  for (let x = b.minX; x <= b.maxX; x++) for (let z = b.minZ; z <= b.maxZ; z++) for (let y = 39; y <= 61; y++) { const n = at(x, y, z); if (n === 'gold_block') gold++; else if (n === 'sea_lantern') lanterns++; }
  const elders = [...outs.values()].flatMap((o) => o.entities).filter((e) => e.id === 'elder_guardian');
  check('the generator builds it: eight gold blocks, the lanterns, three elders', gold === 8 && lanterns > 50 && elders.length === 3, `${gold} gold, ${lanterns} lanterns, ${elders.length} elders`);
  const CH = { prismarine: '#', prismarine_bricks: '=', dark_prismarine: '%', sea_lantern: '*', gold_block: 'G', wet_sponge: 's', water: ' ', gravel: '.', sand: '.', stone: ':' };
  for (let z = b.minZ - 2; z <= b.maxZ + 2; z += 1) {
    let row = '';
    for (let x = b.minX - 2; x <= b.maxX + 2; x++) {
      let ch = '?';
      for (let y = 62; y >= 30; y--) { const n = at(x, y, z); if (n === 'water' || n === 'air' || n === 'seagrass' || n === 'tall_seagrass' || n === 'kelp' || n === 'kelp_plant') continue; ch = CH[n] ?? n[0]; break; }
      row += ch;
    }
    console.log(row);
  }
}

console.log(fails ? `${fails} FAILED` : 'all ok');
await close();
process.exit(fails ? 1 : 0);
